#!/bin/bash

set -euo pipefail
umask 077

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG_DIR="$ROOT/Config"
CONFIG_PATH="$CONFIG_DIR/Local.xcconfig"

usage() {
  cat <<'EOF'
Usage: Scripts/configure-local-signing.sh --bundle-id <unique.reverse.dns.id> [--team-id <TEAM_ID>]

Creates the ignored Config/Local.xcconfig used automatically by Xcode. It does
not edit the Xcode project or source files, contact Apple, register identifiers,
or change signing settings outside this repository.

Examples:
  Scripts/configure-local-signing.sh --bundle-id com.yourname.CodexRateWidget
  Scripts/configure-local-signing.sh --bundle-id com.yourname.CodexRateWidget --team-id "YOUR_TEAM_ID"
EOF
}

fail() {
  echo "error: $*" >&2
  exit 1
}

bundle_id=""
team_id=""

while (( $# > 0 )); do
  case "$1" in
    --bundle-id)
      (( $# >= 2 )) || fail "--bundle-id requires a value"
      bundle_id="$2"
      shift 2
      ;;
    --team-id)
      (( $# >= 2 )) || fail "--team-id requires a value"
      team_id="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "unknown argument: $1"
      ;;
  esac
done

[[ -n "$bundle_id" ]] || fail "--bundle-id is required"
[[ "$bundle_id" == *.* ]] || fail "bundle ID must use reverse-DNS form"
[[ "$bundle_id" != *..* ]] || fail "bundle ID must not contain empty components"
[[ "$bundle_id" =~ ^[A-Za-z0-9][A-Za-z0-9.-]*[A-Za-z0-9]$ ]] \
  || fail "bundle ID may contain only letters, numbers, hyphens, and periods"
[[ "$bundle_id" != com.example.* ]] \
  || fail "replace com.example with a reverse-DNS namespace you control"

if [[ -n "$team_id" && ! "$team_id" =~ ^[A-Z0-9]{10}$ ]]; then
  fail "Team ID must contain exactly 10 uppercase letters or numbers"
fi

mkdir -p "$CONFIG_DIR"

if git -C "$ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1 \
  && ! git -C "$ROOT" check-ignore --quiet -- Config/Local.xcconfig; then
  fail "Config/Local.xcconfig is not ignored; refusing to write personal signing settings"
fi

temporary_config="$CONFIG_PATH.tmp.$$"
trap 'rm -f "$temporary_config"' EXIT

{
  echo "// Generated by Scripts/configure-local-signing.sh. Do not commit."
  echo "CODEX_RATE_WIDGET_BUNDLE_ID = $bundle_id"
  echo "CODEX_RATE_WIDGET_DEVELOPMENT_TEAM = $team_id"
} > "$temporary_config"

chmod 600 "$temporary_config"
mv "$temporary_config" "$CONFIG_PATH"
trap - EXIT

cat <<EOF
Created ignored local configuration:
  $CONFIG_PATH

Resolved identifiers:
  App:       $bundle_id
  Extension: $bundle_id.Widget
  Tests:     $bundle_id.Tests
  App Group: \$(TeamIdentifierPrefix)$bundle_id

Config/Shared.xcconfig includes this file automatically. Open the project in
Xcode or run xcodebuild normally; no -xcconfig argument is required.

The tracked repository was not modified. Check with: git status --short
EOF
